# /opt/monitoring-configs/mimir/config.yaml
multitenancy_enabled: false

# Настройки сервера
server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info

# Настройки хранилища блоков
blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks
  bucket_store:
    sync_dir: /data/tsdb-sync
  tsdb:
    dir: /data/tsdb
    retention_period: 720h  # 30 дней

# Настройки дистрибьютора
distributor:
  ring:
    kvstore:
      store: memberlist

# Настройки ingester
ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

# Настройки querier
querier:
  query_store_after: 12h

# Настройки ruler
ruler:
  alertmanager_url: http://alertmanager:9093

# Базовая конфигурация компактора Mimir

# Параметры блоков компакции
compactor:
  # Интервалы компакции блоков 
  block_ranges: 
    - 2h
    - 12h
    - 24h

  # Директория для временного хранения блоков при компакции
  data_dir: /data/compactor

  # Интервал запуска компакции
  compaction_interval: 1h

  # Количество попыток при неудачной компакции
  compaction_retries: 3

  # Максимальное количество параллельных компакций
  compaction_concurrency: 1

  # Период ожидания перед компакцией первоуровневых блоков
  first_level_compaction_wait_period: 25m

  # Интервал очистки блоков
  cleanup_interval: 15m

  # Максимальное количество tenant для параллельной очистки
  cleanup_concurrency: 20

  # Задержка перед удалением блоков
  deletion_delay: 12h

  # Параметры шардинга
  sharding_ring:
    kvstore:
      store: memberlist

# Настройки memberlist
memberlist:
  join_members: ["mimir:7946"]
