server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info

multitenancy_enabled: true

memberlist:
  abort_if_cluster_join_fails: false
  join_members: []

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /data/tsdb-sync
  filesystem:
    dir: /data/tsdb

compactor:
  data_dir: /data/compactor
  compaction_interval: 1h
  retention_enabled: true  # Если ваша сборка поддерживает удаление устаревших данных

limits:
  retention_period: 720h
  max_global_series_per_user: 1000000
  max_global_series_per_metric: 100000
  max_fetched_series_per_query: 5000
  max_fetched_chunk_bytes_per_query: 2147483648
  max_samples_per_query: 1000000

distributor:
  pool:
    health_check_ingesters: true
    client_cleanup_period: 15s

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

alertmanager:
  external_url: http://mimir.horecasoft.ru/alertmanager
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir/alertmanager-fallback.yaml

ruler:
  external_url: http://mimir.horecasoft.ru
  alertmanager_url: http://alertmanager:9093
  enable_api: true

query_frontend:
  log_queries_longer_than: 10s
  parallelise_shardable_queries: true

analytics:
  reporting_enabled: false
